/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: e0eddbccccb0eccaae0b409ed6a98918)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	JOB_QUEUE: Queue;
	EMAIL_FROM: string;
	BETTER_AUTH_URL: string;
	BETTER_AUTH_SECRET: string;
	FOLIOTRACE_ENCRYPTION_KEY: string;
	AUTH_ALLOW_UNVERIFIED_LOCAL: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMAIL_FROM" | "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET" | "FOLIOTRACE_ENCRYPTION_KEY" | "AUTH_ALLOW_UNVERIFIED_LOCAL">> {}
}
