CREATE TABLE projects(id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES user(id), title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL);
CREATE INDEX project_owner ON projects(owner_id);
CREATE TABLE upload_receipts(id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES user(id), project_id TEXT NOT NULL REFERENCES projects(id), object_path TEXT NOT NULL UNIQUE, media_type TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE sources(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), title TEXT NOT NULL, object_path TEXT NOT NULL UNIQUE, media_type TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(id,project_id));
CREATE TABLE source_versions(id TEXT PRIMARY KEY, source_id TEXT NOT NULL, project_id TEXT NOT NULL, revision INTEGER NOT NULL CHECK(revision>0), pages TEXT NOT NULL CHECK(json_valid(pages)), method TEXT NOT NULL CHECK(method IN ('import','manual','restore','ocr-reviewed')), created_at TEXT NOT NULL, FOREIGN KEY(source_id,project_id) REFERENCES sources(id,project_id), UNIQUE(source_id,revision), UNIQUE(id,source_id,project_id));
CREATE TABLE notes(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), parent_id TEXT UNIQUE, revision INTEGER NOT NULL CHECK(revision>0), title TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(id,project_id), FOREIGN KEY(parent_id,project_id) REFERENCES notes(id,project_id));
CREATE TABLE evidence(id TEXT PRIMARY KEY, project_id TEXT NOT NULL, source_id TEXT NOT NULL, version_id TEXT NOT NULL, page INTEGER NOT NULL CHECK(page>0), quote TEXT NOT NULL, question TEXT NOT NULL, interpretation TEXT NOT NULL, relation TEXT NOT NULL CHECK(relation IN ('supports','challenges','context')), created_at TEXT NOT NULL, FOREIGN KEY(version_id,source_id,project_id) REFERENCES source_versions(id,source_id,project_id));
CREATE TABLE model_connections(id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES user(id), label TEXT NOT NULL, provider TEXT NOT NULL, model_id TEXT NOT NULL, vision INTEGER NOT NULL, key_hint TEXT NOT NULL, encrypted_key TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE research_runs(id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES user(id), project_id TEXT NOT NULL REFERENCES projects(id), kind TEXT NOT NULL CHECK(kind IN ('analysis','ocr')), status TEXT NOT NULL CHECK(status IN ('running','succeeded','failed')), prompt TEXT NOT NULL, model_snapshot TEXT NOT NULL CHECK(json_valid(model_snapshot)), source_version_ids TEXT NOT NULL CHECK(json_valid(source_version_ids)), result TEXT, error TEXT, input_tokens INTEGER NOT NULL DEFAULT 0, output_tokens INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, finished_at TEXT);
CREATE UNIQUE INDEX one_running_task_per_user ON research_runs(owner_id) WHERE status='running';
CREATE INDEX source_project ON sources(project_id);
CREATE INDEX version_project ON source_versions(project_id);
CREATE INDEX note_project ON notes(project_id);
CREATE INDEX evidence_project ON evidence(project_id);
CREATE INDEX run_project ON research_runs(project_id);
CREATE INDEX model_owner ON model_connections(owner_id);
CREATE TRIGGER immutable_source_update BEFORE UPDATE ON sources BEGIN SELECT RAISE(ABORT,'Originals are immutable'); END;
CREATE TRIGGER immutable_version_update BEFORE UPDATE ON source_versions BEGIN SELECT RAISE(ABORT,'Versions are immutable'); END;
CREATE TRIGGER immutable_version_delete BEFORE DELETE ON source_versions BEGIN SELECT RAISE(ABORT,'Versions are immutable'); END;
CREATE TRIGGER immutable_note_update BEFORE UPDATE ON notes BEGIN SELECT RAISE(ABORT,'Notes are immutable'); END;
CREATE TRIGGER immutable_note_delete BEFORE DELETE ON notes BEGIN SELECT RAISE(ABORT,'Notes are immutable'); END;
CREATE TRIGGER immutable_evidence_update BEFORE UPDATE ON evidence BEGIN SELECT RAISE(ABORT,'Evidence is immutable'); END;
