import { writeFileSync } from 'node:fs';

// Original folded-paper silhouette. Angled paper edges, open lower ribs and
// the two guard sticks are structural; no letter is drawn over the fan.
function fan(count, compact = false) {
  const p = (angle, radius) => {
    const a = (angle * Math.PI) / 180;
    return `${(56 + radius * Math.sin(a)).toFixed(2)} ${(66 - radius * Math.cos(a)).toFixed(2)}`;
  };
  const folds = [];
  const spread = 124;
  const gap = compact ? 0.85 : 0.32;
  for (let i = 0; i < count; i++) {
    const a = -62 + (spread * i) / count + gap;
    const b = -62 + (spread * (i + 1)) / count - gap;
    const mid = (a + b) / 2;
    folds.push({
      d: `M${p(a, 57.8)}L${p(mid, 59)}L${p(b, 57.8)}L${p(b, 19)}Q${p(mid, 18.3)} ${p(a, 19)}Z`,
      opacity: 1,
    });
    if (!compact)
      folds.push({
        d: `M${p(mid, 59)}L${p(b, 57.8)}L${p(b, 19)}L${p(mid, 18.65)}Z`,
        opacity: 0.13,
        shade: true,
      });
  }
  const ribs = Array.from({ length: count - 1 }, (_, i) => {
    const a = -62 + (spread * (i + 1)) / count;
    return `M${p(a, 3.3)}L${p(a, 17.4)}`;
  }).join('');
  const guard = `M${p(-62, 59)}L${p(-62, 2.2)}Q56 67.8 ${p(62, 2.2)}L${p(62, 59)}`;
  return { folds, ribs, guard };
}

// Bespoke lowercase lettering: open c, single-storey a, a narrow n and a
// broad, gently joined w. The two o counters are softened squares, not circles.
const word = [
  'M26 11C23.6 8 20.4 6.7 16.2 6.7C8.7 6.7 4.3 12.1 4.3 20.8C4.3 29.5 8.7 34.9 16.2 34.9C20.4 34.9 23.6 33.4 26 30.4',
  'M58.9 4.2V37.4M58.9 20.8C58.9 12.1 54.6 6.7 47.1 6.7C39.6 6.7 35.1 12.1 35.1 20.8C35.1 29.5 39.6 34.9 47.1 34.9C54.6 34.9 58.9 29.5 58.9 20.8',
  'M71.1 37.4V4.2M71.1 19.1C71.1 11.4 75.6 6.7 82.1 6.7C89.1 6.7 92.4 11 92.4 18.3V37.4',
  'M103.6 5L111.4 34.15Q111.9 35.55 113.2 34.15L121.4 12.2L129.6 34.15Q130.3 35.55 131.3 34.15L139.1 5',
  'M171.9 20.8C171.9 11.6 167.5 6.7 159.8 6.7C152.1 6.7 147.7 11.6 147.7 20.8C147.7 30 152.1 34.9 159.8 34.9C167.5 34.9 171.9 30 171.9 20.8Z',
  'M206.8 20.8C206.8 11.6 202.4 6.7 194.7 6.7C187 6.7 182.6 11.6 182.6 20.8C182.6 30 187 34.9 194.7 34.9C202.4 34.9 206.8 30 206.8 20.8Z',
];
// Eleven leaves create ten internal ribs between the two guard sticks.
const main = fan(11);
const compact = fan(11, true);
// The browser tab renders at about 16px: keep its simpler optical variant.
const favicon = fan(9, true);
const svgBody = (art, small = false) =>
  art.folds
    .map(
      (f) =>
        `<path d="${f.d}" fill="${f.shade ? '#201b12' : 'currentColor'}" opacity="${f.opacity}"/>`,
    )
    .join('') +
  `<path d="${art.ribs}" fill="none" stroke="currentColor" stroke-width="${small ? 1.3 : 0.8}" stroke-linecap="round"/><path d="${art.guard}" fill="none" stroke="currentColor" stroke-width="${small ? 2.2 : 1.65}" stroke-linecap="round" stroke-linejoin="round"/><circle cx="56" cy="66" r="1.8" fill="currentColor"/>`;
const svg = (body, viewBox, extra = '') =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" ${extra}>${body}</svg>\n`;
writeFileSync(
  'lib/brand-art.ts',
  `// Generated by scripts/build-brand.mjs. Edit geometry there.\nexport const fanArt = ${JSON.stringify(main, null, 2)};\nexport const compactFanArt = ${JSON.stringify(compact, null, 2)};\nexport const wordmarkPaths = ${JSON.stringify(word, null, 2)};\n`,
);
writeFileSync(
  'public/brand/canwoo-mark.svg',
  svg(svgBody(main), '0 0 112 72', 'color="#9b7a3f"'),
);
writeFileSync(
  'public/brand/canwoo-wordmark.svg',
  svg(
    `<g fill="none" stroke="currentColor" stroke-width="5.5" stroke-linecap="butt" stroke-linejoin="round">${word.map((d) => `<path d="${d}"/>`).join('')}</g>`,
    '0 0 212 42',
    'color="#252824"',
  ),
);
const icon = svg(
  `<style>:root{color:#91703b}@media(prefers-color-scheme:dark){:root{color:#d3b783}}</style><g transform="translate(2 12) scale(.5357)">${svgBody(favicon, true)}</g>`,
  '0 0 64 64',
);
writeFileSync('public/icon.svg', icon);
writeFileSync('public/favicon.svg', icon);
