import { writeFileSync } from 'node:fs';

// Original folded-paper silhouette. Angled paper edges, open lower ribs and
// the two guard sticks are structural; no letter is drawn over the fan.
function fan(count, compact = false) {
  const p = (angle, radius) => {
    const a = (angle * Math.PI) / 180;
    return `${(56 + radius * Math.sin(a)).toFixed(2)} ${(66 - radius * Math.cos(a)).toFixed(2)}`;
  };
  const folds = [];
  const spread = 124;
  const gap = compact ? 0.85 : 0.32;
  for (let i = 0; i < count; i++) {
    const a = -62 + (spread * i) / count + gap;
    const b = -62 + (spread * (i + 1)) / count - gap;
    const mid = (a + b) / 2;
    folds.push({
      d: `M${p(a, 57.8)}L${p(mid, 59)}L${p(b, 57.8)}L${p(b, 19)}Q${p(mid, 18.3)} ${p(a, 19)}Z`,
      opacity: 1,
    });
    if (!compact)
      folds.push({
        d: `M${p(mid, 59)}L${p(b, 57.8)}L${p(b, 19)}L${p(mid, 18.65)}Z`,
        opacity: 0.13,
        shade: true,
      });
  }
  const ribs = Array.from({ length: count - 1 }, (_, i) => {
    const a = -62 + (spread * (i + 1)) / count;
    return `M${p(a, 3.3)}L${p(a, 17.4)}`;
  }).join('');
  const guard = `M${p(-62, 59)}L${p(-62, 2.2)}Q56 67.8 ${p(62, 2.2)}L${p(62, 59)}`;
  return { folds, ribs, guard };
}

// Eleven leaves create ten internal ribs between the two guard sticks.
const main = fan(11);
const compact = fan(11, true);
// The browser tab renders at about 16px: keep its simpler optical variant.
const favicon = fan(9, true);
const svgBody = (art, small = false) =>
  art.folds
    .map(
      (f) =>
        `<path d="${f.d}" fill="${f.shade ? '#201b12' : 'currentColor'}" opacity="${f.opacity}"/>`,
    )
    .join('') +
  `<path d="${art.ribs}" fill="none" stroke="currentColor" stroke-width="${small ? 1.3 : 0.8}" stroke-linecap="round"/><path d="${art.guard}" fill="none" stroke="currentColor" stroke-width="${small ? 2.2 : 1.65}" stroke-linecap="round" stroke-linejoin="round"/><circle cx="56" cy="66" r="1.8" fill="currentColor"/>`;
const svg = (body, viewBox, extra = '') =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" ${extra}>${body}</svg>\n`;
writeFileSync(
  'lib/brand-art.ts',
  `// Generated by scripts/build-brand.mjs. Edit geometry there.\nexport const fanArt = ${JSON.stringify(main, null, 2)};\nexport const compactFanArt = ${JSON.stringify(compact, null, 2)};\n`,
);
writeFileSync(
  'public/brand/canwoo-mark.svg',
  svg(svgBody(main), '0 0 112 72', 'color="#9b7a3f"'),
);
const icon = svg(
  `<style>:root{color:#91703b}@media(prefers-color-scheme:dark){:root{color:#d3b783}}</style><g transform="translate(2 12) scale(.5357)">${svgBody(favicon, true)}</g>`,
  '0 0 64 64',
);
writeFileSync('public/icon.svg', icon);
writeFileSync('public/favicon.svg', icon);
